# Generated by Django 3.2.6 on 2021-08-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200422_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.CharField(default='artigo.jpg', max_length=20),
            preserve_default=False,
        ),
    ]
